name: Deploy Beta
on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: "development"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: "development"
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy Prod
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:beta-portfolio
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
